version: '3'

services:
  db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - database_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  flyway:
    image: flyway/flyway
    command: -configFiles=./conf/flyway.config -locations=filesystem:./sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/flyway/conf:/flyway/conf
      - ${PWD}/flyway/sql:/flyway/sql
    depends_on:
      - db

volumes:
  database_data:
    driver: local
