version: '3'
services:
  oracledb:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./setup:/docker-entrypoint-initdb.d/setup
      - ./startup:/docker-entrypoint-initdb.d/startup
    environment:
      - ORACLE_PWD=Password
    ports:
      - 1521:1521
      - 5500:5500
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo 'select 1 from dual;' | sqlplus -s pdbadmin/Password@XEPDB1" ]
      interval: 10s
      timeout: 10s
      retries: 60
      start_period: 60s
volumes:
  oracle_data: