-- objects.sql
ALTER SESSION SET CONTAINER = MYDB;
ALTER SESSION SET CURRENT_SCHEMA = myuser;

CREATE TABLE EMPLOYEE
(
    ID INT ,
    NAME CHARACTER (100)
);

INSERT INTO EMPLOYEE VALUES(1,'Homer');
INSERT INTO EMPLOYEE VALUES(2,'Bart');

COMMIT;

SELECT ID,NAME FROM EMPLOYEE;